<div class="wrap">
	<div class="layoutBox">
		<div class="box _a">
			<div class="a_border">
				<p class="title"><?=$title[0]?></p>
				<p class="sub_title"><?=$sub_title[0]?></p>
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<div class="b_price">
					<p class="price">原價<span style="font-family: 'Open Sans'"><?=$price?></span></p>
					<p class="sale_price">特價<br><span><?=$sale?></span></p>
				</div>
				<img alt="" class="logo" src="style/images/bottom_a.png"></div>
		</div>
		<div class="box _b">
			<div class="b_border">
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<p class="title"><?=$title[1]?></p>
				<p class="sub_title"><?=$sub_title[1]?></p>
				<p class="sale_price">特 <br>價<span><?=$sale?></span></p>
				<img alt="" class="logo" src="style/images/bottom_b.png"></div>
		</div>
		<div class="box _c">
			<div class="c_border">
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<p class="title"><?=$title[2]?></p>
				<p class="sale_price">特價
					<span><?=$sale?></span></p>
				<img alt="" class="logo" src="style/images/bottom_c.png"></div>
		</div>
		<div class="box _d">
			<div class="d_border">
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<div class="d_price">
					<p class="title"><?=$title[3]?></p>
					<p class="sub_title"><?=$sub_title[3]?></p>
					<p class="sale_price">特價
						<span><?=$sale?></span></p>
					<p class="price">原價<span><?=$price?></span></p>
				</div>
				<img alt="" class="logo" src="style/images/bottom_d.png"></div>
		</div>
		<div class="box _e">
			<div class="e_border">
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<div class="b_price">
					<p class="title"><?=$title[4]?></p>
					<p class="sub_title"><?=$sub_title[4]?></p>
				</div>
				<img alt="" class="logo" src="style/images/bottom_e.png">
				<p class="sale_price">特價
					<span><?=$sale?></span></p>
				<p class="price">原價<span><?=$price?></span></p>
			</div>
		</div>
		<div class="box _f">
			<div class="f_border">
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<p class="title"><?=parseChinese("{$title[5]} {$sub_title[5]}", 5)?></p>
				<div class="b_price">
					<p class="sale_price">特價<br><span><?=$sale?></span></p>
					<p class="price">原價<span><?=$price?></span></p>
				</div>
				<img alt="" class="logo" src="style/images/bottom_f.png"></div>
		</div>
		<div class="box _g">
			<div class="g_border">
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<p class="title"><?=parseChinese("{$title[6]} {$sub_title[6]}", 6)?></p>
				<div class="b_price">
					<p class="sale_price">特價<br><span><?=$sale?></span></p>
					<p class="price">原價<span><?=$price?></span></p>
				</div>
				<img alt="" class="logo" src="style/images/bottom_g.png"></div>
		</div>
		<div class="box _h">
			<div class="h_border">
				<p class="title"><?=$title[7]?></p>
				<p class="sub_title"><?=$sub_title[7]?></p>
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<div class="word">
					<img alt="" src="style/images/h_word.png"></div>
				<div class="b_price">
					<p class="sale_price">特價<br><span><?=$sale?></span></p>
					<p class="price">原價<span><?=$price?></span></p>
				</div>
				<img alt="" class="logo" src="style/images/bottom_h.png"></div>
		</div>
		<div class="box _i">
			<div class="i_border">
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<p class="title"><?=$title[8]?></p>
				<p class="sale_price">特價
					<span><?=$sale?></span></p>
				<img alt="" class="logo" src="style/images/bottom_i.png"></div>
		</div>
		<div class="box _j">
			<div class="j_border">
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<div class="b_price">
					<p class="title"><?=$title[9]?></p>
					<p class="sub_title"><?=$sub_title[9]?></p>
				</div>
				<div class="word">
					<img alt="" src="style/images/j_word.png"></div>
				<p class="sale_price">特價
					<span><?=$sale?></span></p>
				<p class="price">原價<span><?=$price?></span></p>
				<img alt="" class="logo" src="style/images/bottom_j.png"></div>
		</div>
		<div class="box _k">
			<div class="k_border">
				<p class="title"><?=$title[10]?></p>
				<p class="sub_title"><?=$sub_title[10]?></p>
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<div class="b_price">
					<p class="price">原價<span><?=$price?></span></p>
					<p class="sale_price">特價<br><span><?=$sale?></span></p>
				</div>
				<img alt="" class="logo" src="style/images/bottom_k.png"></div>
		</div>
		<div class="box _l">
			<div class="l_border">
				<p class="title"><?=$title[11]?></p>
				<p class="sub_title"><?=$sub_title[11]?></p>
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<div class="b_price">
					<p class="price">原價<span><?=$price?></span></p>
					<p class="sale_price">特價<br><span><?=$sale?></span></p>
				</div>
				<div class="word">
					<img alt="" src="style/images/l_word.png"></div>
				<img alt="" class="logo" src="style/images/bottom_l.png"></div>
		</div>
		<div class="box _m">
			<div class="m_border">
				<p class="title"><?=$title[12]?></p>
				<p class="sub_title"><?=$sub_title[12]?></p>
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<div class="b_price">
					<p class="price">原價<span><?=$price?></span></p>
					<p class="sale_price">特價<br><span><?=$sale?></span></p>
				</div>
				<div class="word">
					<img alt="" src="style/images/m_word.png"></div>
				<img alt="" class="logo" src="style/images/bottom_m.png"></div>
		</div>
		<div class="box _n">
			<div class="n_border">
				<p class="title"><?=$title[13]?></p>
				<p class="sub_title"><?=$sub_title[13]?></p>
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<p class="sale_price">特價<br><span><?=$sale?></span></p>
				<p class="price">原價<span><?=$price?></span></p>
				<img alt="" class="logo" src="style/images/bottom_n.png"></div>
		</div>
		<div class="box _o">
			<div class="o_border">
				<p class="title"><?=$title[14]?></p>
				<p class="sub_title"><?=$sub_title[14]?></p>
				<div class="pic">
					<img alt="" src="<?=$image?>"></div>
				<p class="sale_price">特價<br><span><?=$sale?></span></p>
				<p class="price">原價<span><?=$price?></span></p>
				<img alt="" class="logo" src="style/images/bottom_o.png"></div>
		</div>
	</div>
</div>
