<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>GoogleAD</title>

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

		<script src="js/ajaxfileupload.js"></script>
		<link href="style/layout.css" rel="stylesheet" type="text/css">
	</head>

</html>
<body>
	<div class="BD">
		<div class="intBox">
			<form action="#" method="post" target="_blank">
				<p class="btnBox">
					<span class="btn_view">
						<a href="#" id="same_title">標題同一</a></span>
					<span class="btn_view">
						<a href="#" id="submit1" style="display:none;">送出預覽</a>
						<a href="#" id="submit2">送出預覽</a></span>
				</p>
				<table>
					<input style="float:right;" type="button" id="change" value="上傳圖檔orURL">
					<tr style="text-align:right;display:none;" id="if">
						<th>上傳商品圖片</th>
						<td>
							<input type="file" id="pdImg" name="pdImg">
						</td>
					</tr>
					<tr style="text-align:right;" id="iu">
						<th>上傳商品圖片url</th>
						<td>
							<input type="text" id="imgUrl" name="imgUrl" value="{$image}">
						</td>
					</tr>

					<tr>
						<td colspan="2">
							<div class="price_group">
								<span>原價 NT.</span>
								<input type="number" name="price">
							</div>
							<div class="price_group">
								<span>特價 NT.</span>
								<input type="number" name="sale">
							</div>
						</td>
					</tr>

					<tr>
						<th>a.標題 300x250</th>
						<td class="input_group">
							<input type="text" name="title1_1" placeholder="上限中文七字元">
							<input type="text" name="title1_2" placeholder="可以多放中文九字元">
						</td>
					</tr>

					<tr>
						<th>b.標題 320x100</th>
						<td class="input_group">
							<input type="text" name="title2_1" placeholder="上限中文七字元">
							<input type="text" name="title2_2" placeholder="可以多放中文九字元">
						</td>
					</tr>

					<tr>
						<th>c.標題 320x50</th>
						<td style="color:#9e9e9e">版型限制無標題</td>
					</tr>

					<tr>
						<th>d.標題 728x90</th>
						<td class="input_group">
							<input type="text" name="title4_1" placeholder="上限中文七字元">
							<input type="text" name="title4_2" placeholder="可以多放中文九字元">
						</td>
					</tr>

					<tr>
						<th>e.標題 970x90</th>
						<td class="input_group">
							<input type="text" name="title5_1" placeholder="上限中文七字元">
							<input type="text" name="title5_2" placeholder="可以多放中文九字元">
						</td>
					</tr>

					<tr>
						<th>f.標題 120x600</th>
						<td class="input_group">
							<input type="text" name="title6_1" placeholder="上限中文七字元">
							<input type="text" name="title6_2" placeholder="可以多放中文九字元">
						</td>
					</tr>

					<tr>
						<th>g.標題 160x600</th>
						<td class="input_group">
							<input type="text" name="title7_1" placeholder="上限中文七字元">
							<input type="text" name="title7_2" placeholder="可以多放中文九字元">
						</td>
					</tr>

					<tr>
						<th>h.標題 240x400</th>
						<td class="input_group">
							<input type="text" name="title8_1" placeholder="上限中文七字元">
							<input type="text" name="title8_2" placeholder="可以多放中文九字元">
						</td>
					</tr>
					<tr>
						<th>i.標題 468x60</th>
						<td class="input_group">
							<input type="text" name="title9_1" placeholder="上限中文七字元">
							<input type="text" name="title9_2" placeholder="可以多放中文九字元">
						</td>
					</tr>
					<tr>
						<th>j.標題 970x250</th>
						<td class="input_group">
							<input type="text" name="title10_1" placeholder="上限中文七字元">
							<input type="text" name="title10_2" placeholder="可以多放中文九字元">
						</td>
					</tr>
					<tr>
						<th>k.標題 336x280</th>
						<td class="input_group">
							<input type="text" name="title11_1" placeholder="上限中文七字元">
							<input type="text" name="title11_2" placeholder="可以多放中文九字元">
						</td>
					</tr>
					<tr>
						<th>l.標題 250x250</th>
						<td class="input_group">
							<input type="text" name="title12_1" placeholder="上限中文七字元">
							<input type="text" name="title12_2" placeholder="可以多放中文九字元">
						</td>
					</tr>
					<tr>
						<th>m.標題 200x200</th>
						<td class="input_group">
							<input type="text" name="title13_1" placeholder="上限中文七字元">
							<input type="text" name="title13_2" placeholder="可以多放中文九字元">
						</td>
					</tr>
					<tr>
						<th>n.標題 300x600</th>
						<td class="input_group">
							<input type="text" name="title14_1" placeholder="上限中文七字元">
							<input type="text" name="title14_2" placeholder="可以多放中文九字元">
						</td>
					</tr>
					<tr>
						<th>o.標題 300x1050</th>
						<td class="input_group">
							<input type="text" name="title15_1" placeholder="上限中文七字元">
							<input type="text" name="title15_2" placeholder="可以多放中文九字元">
						</td>
					</tr>
				</table>
			</form>
		</div>
	</div>
</body>
